<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Spray Foam Estimator</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="bg-light">
    <div class="container mt-5">
        <h2 class="text-center">Spray Foam Insulation Estimator</h2>
        <div class="card p-4 mt-3">
            <form method="POST">
                <div class="mb-3">
                    <label class="form-label">Length (ft)</label>
                    <input type="number" class="form-control" name="length" required>
                </div>
                <div class="mb-3">
                    <label class="form-label">Width (ft)</label>
                    <input type="number" class="form-control" name="width" required>
                </div>
                <div class="mb-3">
                    <label class="form-label">Height (ft)</label>
                    <input type="number" class="form-control" name="height" required>
                </div>
                <div class="mb-3">
                    <label class="form-label">Insulation Type</label>
                    <select class="form-control" name="insulation_type" required>
                        <option value="open-cell">Open-Cell</option>
                        <option value="closed-cell">Closed-Cell</option>
                    </select>
                </div>
                <div class="mb-3">
                    <label class="form-label">Location Factor (1.0 = standard)</label>
                    <input type="number" step="0.1" class="form-control" name="location_factor" value="1.0" required>
                </div>
                <button type="submit" class="btn btn-primary w-100">Calculate Estimate</button>
            </form>
        </div>

        {% if estimate %}
        <div class="card p-4 mt-4">
            <h4 class="text-center">Estimate Results</h4>
            <table class="table table-bordered mt-3">
                {% for key, value in estimate.items() %}
                <tr>
                    <td><strong>{{ key }}</strong></td>
                    <td>{{ value }}</td>
                </tr>
                {% endfor %}
            </table>
            <a href="{{ url_for('download_pdf', **estimate) }}" class="btn btn-success w-100">Download PDF Quote</a>
        </div>
        {% endif %}

        {% if error %}
        <div class="alert alert-danger mt-3">{{ error }}</div>
        {% endif %}
    </div>
</body>
</html>
